/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEND;

/**
 *
 * @author Tech Line
 */
public class Rigister extends javax.swing.JFrame {

    /**
     * Creates new form Rigister
     */
    public Rigister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        registerBut = new javax.swing.JButton();
        registerBut1 = new javax.swing.JButton();
        exitBtn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Create = new javax.swing.JButton();
        welMess = new javax.swing.JLabel();
        quOne = new javax.swing.JLabel();
        yesOneChe = new javax.swing.JRadioButton();
        noOneChe1 = new javax.swing.JRadioButton();
        quOne1 = new javax.swing.JLabel();
        yesOneChe2 = new javax.swing.JRadioButton();
        noOneChe2 = new javax.swing.JRadioButton();
        quOne3 = new javax.swing.JLabel();
        nameCar = new javax.swing.JTextField();
        quOne4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        quOne5 = new javax.swing.JLabel();
        yearCar = new javax.swing.JTextField();
        quOne6 = new javax.swing.JLabel();
        quOne7 = new javax.swing.JLabel();
        numberPlateCar = new javax.swing.JTextField();
        quOne8 = new javax.swing.JLabel();
        numberYears = new javax.swing.JTextField();
        Color = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(241, 237, 230));

        jPanel1.setBackground(new java.awt.Color(172, 156, 141));

        registerBut.setBackground(new java.awt.Color(241, 237, 230));
        registerBut.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        registerBut.setText("Rigister");

        registerBut1.setBackground(new java.awt.Color(241, 237, 230));
        registerBut1.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        registerBut1.setText("Serching");
        registerBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBut1ActionPerformed(evt);
            }
        });

        exitBtn1.setBackground(new java.awt.Color(241, 237, 230));
        exitBtn1.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        exitBtn1.setText("Exit");
        exitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(registerBut)
                .addGap(18, 18, 18)
                .addComponent(registerBut1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn1)
                .addGap(409, 409, 409))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBut)
                    .addComponent(registerBut1)
                    .addComponent(exitBtn1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(172, 156, 141));

        Create.setBackground(new java.awt.Color(239, 233, 225));
        Create.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        Create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        Create.setText("Add");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        welMess.setBackground(new java.awt.Color(255, 255, 255));
        welMess.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        welMess.setText("Welcome To Car Register");

        quOne.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        quOne.setText("Is it formally entered?");

        yesOneChe.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        yesOneChe.setText("Yes");
        yesOneChe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesOneCheActionPerformed(evt);
            }
        });

        noOneChe1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        noOneChe1.setText("No");
        noOneChe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOneChe1ActionPerformed(evt);
            }
        });

        quOne1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        quOne1.setText("Does he have a partnership contract?");

        yesOneChe2.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        yesOneChe2.setText("Yes");
        yesOneChe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesOneChe2ActionPerformed(evt);
            }
        });

        noOneChe2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        noOneChe2.setText("No");
        noOneChe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOneChe2ActionPerformed(evt);
            }
        });

        quOne3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        quOne3.setText("whose name is the car?");

        nameCar.setBackground(new java.awt.Color(241, 237, 230));
        nameCar.setText("Write the name car");

        quOne4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        quOne4.setText("Model the car:");

        jComboBox1.setBackground(new java.awt.Color(241, 237, 230));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "Truck", "Nikko" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        quOne5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        quOne5.setText("Year:");

        yearCar.setBackground(new java.awt.Color(241, 237, 230));
        yearCar.setText("Write the year car");

        quOne6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        quOne6.setText("Color:");

        quOne7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        quOne7.setText("Number Plate:");

        numberPlateCar.setBackground(new java.awt.Color(241, 237, 230));
        numberPlateCar.setText("Write the Number plate car");
        numberPlateCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberPlateCarActionPerformed(evt);
            }
        });

        quOne8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        quOne8.setText("Number years:");

        numberYears.setBackground(new java.awt.Color(241, 237, 230));
        numberYears.setText("Write the Number plate car");
        numberYears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberYearsActionPerformed(evt);
            }
        });

        Color.setBackground(new java.awt.Color(241, 237, 230));
        Color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White", "Red", "Black", "Gray" }));
        Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(quOne1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yesOneChe2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noOneChe2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(quOne)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yesOneChe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noOneChe1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(quOne3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameCar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(quOne4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(quOne6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(quOne7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberPlateCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(quOne8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(quOne5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearCar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welMess)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(Create)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(welMess)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quOne)
                    .addComponent(yesOneChe)
                    .addComponent(noOneChe1)
                    .addComponent(quOne6)
                    .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quOne1)
                    .addComponent(yesOneChe2)
                    .addComponent(noOneChe2)
                    .addComponent(quOne7)
                    .addComponent(numberPlateCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quOne3)
                    .addComponent(nameCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quOne8)
                    .addComponent(numberYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quOne4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yearCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quOne5)))
                .addGap(71, 71, 71)
                .addComponent(Create)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(612, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerBut1ActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateActionPerformed

    private void yesOneCheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesOneCheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesOneCheActionPerformed

    private void noOneChe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOneChe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOneChe1ActionPerformed

    private void yesOneChe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesOneChe2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesOneChe2ActionPerformed

    private void noOneChe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOneChe2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOneChe2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void numberPlateCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberPlateCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberPlateCarActionPerformed

    private void numberYearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberYearsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberYearsActionPerformed

    private void ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorActionPerformed

    private void exitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtn1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rigister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rigister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rigister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rigister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rigister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Color;
    private javax.swing.JButton Create;
    private javax.swing.JButton exitBtn1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameCar;
    private javax.swing.JRadioButton noOneChe1;
    private javax.swing.JRadioButton noOneChe2;
    private javax.swing.JTextField numberPlateCar;
    private javax.swing.JTextField numberYears;
    private javax.swing.JLabel quOne;
    private javax.swing.JLabel quOne1;
    private javax.swing.JLabel quOne3;
    private javax.swing.JLabel quOne4;
    private javax.swing.JLabel quOne5;
    private javax.swing.JLabel quOne6;
    private javax.swing.JLabel quOne7;
    private javax.swing.JLabel quOne8;
    private javax.swing.JButton registerBut;
    private javax.swing.JButton registerBut1;
    private javax.swing.JLabel welMess;
    private javax.swing.JTextField yearCar;
    private javax.swing.JRadioButton yesOneChe;
    private javax.swing.JRadioButton yesOneChe2;
    // End of variables declaration//GEN-END:variables
}
