/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEND;

/**
 *
 * @author Tech Line
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    public signUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        signup = new javax.swing.JButton();
        login = new javax.swing.JButton();
        passwordSignup = new javax.swing.JTextField();
        usernameSignup = new javax.swing.JTextField();
        fullnameSignup = new javax.swing.JTextField();
        emailSignup = new javax.swing.JTextField();
        addressSignup = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        unL = new javax.swing.JLabel();
        passL = new javax.swing.JLabel();
        messegeError = new javax.swing.JLabel();
        fNlabel = new javax.swing.JLabel();
        emaillabel1 = new javax.swing.JLabel();
        addreslabel1 = new javax.swing.JLabel();
        addreslabel2 = new javax.swing.JLabel();
        phoneSignup = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(241, 237, 230));

        jPanel1.setBackground(new java.awt.Color(172, 156, 141));

        signup.setBackground(new java.awt.Color(239, 233, 225));
        signup.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        signup.setText("Create");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        login.setBackground(new java.awt.Color(239, 233, 225));
        login.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/enter.png"))); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        passwordSignup.setBackground(new java.awt.Color(239, 233, 225));
        passwordSignup.setText("Please write your password");
        passwordSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordSignupFocusLost(evt);
            }
        });
        passwordSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordSignupActionPerformed(evt);
            }
        });

        usernameSignup.setBackground(new java.awt.Color(239, 233, 225));
        usernameSignup.setText("Please write your username");
        usernameSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameSignupFocusLost(evt);
            }
        });
        usernameSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameSignupActionPerformed(evt);
            }
        });

        fullnameSignup.setBackground(new java.awt.Color(239, 233, 225));
        fullnameSignup.setText("Please write your full name");
        fullnameSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fullnameSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fullnameSignupFocusLost(evt);
            }
        });
        fullnameSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameSignupActionPerformed(evt);
            }
        });

        emailSignup.setBackground(new java.awt.Color(239, 233, 225));
        emailSignup.setText("Please write your Email");
        emailSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailSignupFocusLost(evt);
            }
        });
        emailSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailSignupActionPerformed(evt);
            }
        });

        addressSignup.setBackground(new java.awt.Color(239, 233, 225));
        addressSignup.setText("Please write your address");
        addressSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressSignupFocusLost(evt);
            }
        });
        addressSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressSignupActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome To Car Recognition");

        unL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        unL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usrename.png"))); // NOI18N
        unL.setText("Username:");

        passL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        passL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/padlock (1).png"))); // NOI18N
        passL.setText("Password:");

        fNlabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        fNlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/id-card.png"))); // NOI18N
        fNlabel.setText("Full Name:");

        emaillabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        emaillabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mail.png"))); // NOI18N
        emaillabel1.setText("Email:");

        addreslabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        addreslabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/location.png"))); // NOI18N
        addreslabel1.setText("Address:");

        addreslabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        addreslabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/telephone.png"))); // NOI18N
        addreslabel2.setText("Phone:");

        phoneSignup.setBackground(new java.awt.Color(239, 233, 225));
        phoneSignup.setText("Please write your phone");
        phoneSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneSignupFocusLost(evt);
            }
        });
        phoneSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(passL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messegeError, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fNlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emaillabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fullnameSignup)
                                    .addComponent(emailSignup)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(unL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addreslabel2)
                                .addGap(23, 23, 23)
                                .addComponent(phoneSignup)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addreslabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addressSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signup)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNlabel)
                    .addComponent(fullnameSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaillabel1)
                    .addComponent(emailSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unL)
                    .addComponent(usernameSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messegeError)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passL)
                        .addComponent(passwordSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addreslabel1)
                    .addComponent(addressSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addreslabel2)
                    .addComponent(phoneSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup)
                    .addComponent(login))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(476, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(468, 468, 468))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(136, 136, 136))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        login log = new login();
        log.setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_signupActionPerformed

    private void usernameSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameSignupFocusGained
        if(usernameSignup.getText().equals("Please write your username")){
            usernameSignup.setText(null);
        }else{
            usernameSignup.setText("Please write your username");
        }
    }//GEN-LAST:event_usernameSignupFocusGained

    private void usernameSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameSignupFocusLost
        // TODO add your handling code here:
        if(usernameSignup.getText().equals("")){
            usernameSignup.setText("Please write your username");
        }
    }//GEN-LAST:event_usernameSignupFocusLost

    private void usernameSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameSignupActionPerformed

    private void passwordSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordSignupFocusGained
        // TODO add your handling code here:
        if(passwordSignup.getText().equals("Please write your password")){
            passwordSignup.setText(null);
        }else{
            passwordSignup.setText("Please write your password");
        }
    }//GEN-LAST:event_passwordSignupFocusGained

    private void passwordSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordSignupFocusLost
        // TODO add your handling code here:
        if(passwordSignup.getText().equals("")){
            passwordSignup.setText("Please write your password");
        }
    }//GEN-LAST:event_passwordSignupFocusLost

    private void passwordSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordSignupActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_passwordSignupActionPerformed

    private void fullnameSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullnameSignupFocusGained
        // TODO add your handling code here:
        if(fullnameSignup.getText().equals("Please write your full name")){
            fullnameSignup.setText(null);
        }else{
            fullnameSignup.setText("Please write your full name");
        }
        
    }//GEN-LAST:event_fullnameSignupFocusGained

    private void fullnameSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullnameSignupFocusLost
        // TODO add your handling code here:
           if(fullnameSignup.getText().equals("")){
            fullnameSignup.setText("Please write your full name");
        }
    }//GEN-LAST:event_fullnameSignupFocusLost

    private void fullnameSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameSignupActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_fullnameSignupActionPerformed

    private void emailSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailSignupFocusGained
        // TODO add your handling code here:
        if(emailSignup.getText().equals("Please write your Email")){
            emailSignup.setText(null);
        }else{
            emailSignup.setText("Please write your Email");
        }
    }//GEN-LAST:event_emailSignupFocusGained

    private void emailSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailSignupFocusLost
        // TODO add your handling code here:
          if(emailSignup.getText().equals("")){
            emailSignup.setText("Please write your Email");
        }
    }//GEN-LAST:event_emailSignupFocusLost

    private void emailSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailSignupActionPerformed

    private void addressSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressSignupFocusGained
        // TODO add your handling code here:
        if(addressSignup.getText().equals("Please write your address")){
            addressSignup.setText(null);
        }else{
            addressSignup.setText("Please write your address");
        }
    }//GEN-LAST:event_addressSignupFocusGained

    private void addressSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressSignupFocusLost
        if(addressSignup.getText().equals("")){
            addressSignup.setText("Please write your address");
        }
    }//GEN-LAST:event_addressSignupFocusLost

    private void addressSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressSignupActionPerformed

    private void phoneSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneSignupFocusGained
        // TODO add your handling code here:
        if(phoneSignup.getText().equals("Please write your phone")){
            phoneSignup.setText(null);
        }else{
            phoneSignup.setText("Please write your phone");
        }
    }//GEN-LAST:event_phoneSignupFocusGained

    private void phoneSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneSignupFocusLost
        // TODO add your handling code here:  
        if(phoneSignup.getText().equals("")){
            phoneSignup.setText("Please write your phone");
        }
    }//GEN-LAST:event_phoneSignupFocusLost

    private void phoneSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addreslabel1;
    private javax.swing.JLabel addreslabel2;
    private javax.swing.JTextField addressSignup;
    private javax.swing.JTextField emailSignup;
    private javax.swing.JLabel emaillabel1;
    private javax.swing.JLabel fNlabel;
    private javax.swing.JTextField fullnameSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel messegeError;
    private javax.swing.JLabel passL;
    private javax.swing.JTextField passwordSignup;
    private javax.swing.JTextField phoneSignup;
    private javax.swing.JButton signup;
    private javax.swing.JLabel unL;
    private javax.swing.JTextField usernameSignup;
    // End of variables declaration//GEN-END:variables
}
